### ISSUE TITLE
Strings which match patterns in both LOW_SECRET_HINTS and HIGH_SECRET_HINTS are given a 'High' classification.

### ISSUE THREAD

**Issue by ecdavis** [lyft/bandit-high-entropy-string#10]
This means if you have two patterns which match the same string (ex. patterns 'tok' and 'token' both match 'token') that string will be given a High classification due to the duplicate match. This can lead to innocuous strings being overclassified.

**Comment by khanhldt** [comment]
Closing this issue as Lyft team is deprecating this repository.
